config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => 'posts#index'
  resources :users, :only =>[:new, :create]
  resources :sessions, :only =>[:new, :create, :destroy]
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, :presence => true
  validates :article, :presence => true

  belongs_to :user
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  validates :email, :presence => true
  validates_uniqueness_of :email

  has_many :posts

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not Authorized" if current_user.nil?
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

   before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Saved"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post Deleted"
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:name, :article).merge(user_id: current_user.id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in."
    else
      flash.now.alert = "Email or password invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
    flash[:notice] = "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
      flash[:notice] = "login successful"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoSharing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand"><%= link_to "Home", posts_path%></div>
      </div>
      <% if current_user %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text">Logged in as <%= current_user.email %></p></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", signup_path%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", login_path%></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
  <div class ="container">


  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible center" role="alert">
      <%= flash[:notice] %> <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible center" role="alert">
      <%= flash[:alert] %> <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
    </div>
  <% end %>

    <div class = "page-header">
      <h1>Code Tips <small>a blog for those who want easy to understand info</small></h1>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= render("layouts/errors", :object => @post) %>

<%= form_for(@post) do |f| %>
  <div class = 'row'>
    <div class = 'col-md-6'>
      <div class="form-group">
        <%= f.label "Title" %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "Text" %>
    <%= f.text_area :article, :rows =>15, :class => "form-control" %>
  </div>
  <%= f.submit(:class => 'btn btn-success') %>
<% end%>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.sort.reverse.each do |post| %>
  <dt><h3><%= link_to "#{post.name}", post_path(post) %></h3></dt>
  <dl><%= post.article %></dl>
<% end %>

<% if current_user != nil %>
  <%= link_to "New post", new_post_path, :class => 'btn btn-success' %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.name %></h2>
<h5>Author: <%= @user.email%></h5>
<%= @post.article %>
</br>
</br>

<% if current_user == @post.user %>
  <%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-success btn-sm' %>
  <%= link_to "Delete", post_path(@post),
                      :data => { :confirm => "Are you sure you want to delete this post?",
                                :method => "delete"},
                      :class => "btn btn-danger btn-sm" %>
<% end %>

app/views/users/_form.html.erb
<%= render("layouts/errors", :object => @user) %>

<%= form_for(@user) do |f| %>
  <div class ="row">
    <div class ="col-md-6">
      <div class="form-group">
        <%= f.label :email %></br>
        <%= f.text_field :email, :class => "form-control" %>
      </div>
    </div>
  </div>
  <div class ="row">
    <div class ="col-md-6">
      <div class="form-group">
        <%= f.label :password %></br>
        <%= f.password_field :password, :class => "form-control" %>
      </div>
    </div>
  </div>
  <div class ="row">
    <div class ="col-md-6">
      <div class="form-group">
        <%= f.label :password_confirmation %></br>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
      </div>
    </div>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/users/new.html.erb
<div class ="jumbotron">
  <h1>Sign up</h1>
  <%= render 'form' %>
</div>